Repository cesium/seium.org, pull requests merged in 2023-11, with the labels that each got.

#567 refactor: normalize base path gathering
  components/Layout/Layout.tsx
  layout/Manager/Badges/Badges.tsx
  layout/Manager/Identifier/Identifier.tsx
  layout/Manager/Prize/Prize.tsx
  layout/Manager/Prizes/Prizes.tsx
  layout/Sponsor/Dashboard/Dashboard.tsx
  layout/Sponsor/Scanner/Scanner.tsx
  layout/Sponsor/Spotlight/Spotlight.tsx
  layout/Sponsor/Visitors/Visitors.tsx
Labels: bug, moonstone

#568 chore: change managers to staffs
  components/Base/index.jsx
  components/Layout/Layout.tsx
  components/Navbar/index.jsx
  context/Auth/AuthProvider.js
  context/Auth/withAuth.js
  layout/Staff/Badges/Badges.tsx
  layout/Staff/Badges/index.ts
  layout/Staff/Identifier/Identifier.tsx
  layout/Staff/Identifier/index.ts
  layout/Staff/Prize/Prize.tsx
  layout/Staff/Prize/index.ts
  layout/Staff/Prizes/Prizes.tsx
  layout/Staff/Prizes/index.ts
  layout/Staff/components/Award/index.jsx
  layout/Staff/components/StaffRedeemButton/index.jsx
  layout/Staff/components/index.ts
  lib/api.js
  lib/user.js
  pages/manager/badges.js
  pages/manager/identifier.js
  pages/manager/prizes/[uuid].js
  pages/manager/prizes/index.js
  pages/staff/badges.js
  pages/staff/identifier.js
  pages/staff/leaderboard.tsx
  pages/staff/prizes/[uuid].js
  pages/staff/prizes/index.js
Labels: enhancement, priority:medium

#547 refactor: remove back to sei website text from dashboard
  components/Layout/Layout.tsx
Labels: moonstone

#573 refactor: align landing footer
  components/Footer/index.tsx
Labels: enhancement

#577 feat: animate faqs answer opening
  .github/workflows/trello.yml
  layout/FAQs/components/Question/index.tsx
Labels: enhancement

#572 feat: add password visibility button to authentication pages
  components/Input/index.tsx
  components/PasswordInput/index.tsx
  layout/Login/components/LoginForm/index.tsx
  layout/ResetPassword/components/ResetPasswordForm/index.tsx
  layout/SignUp/components/SignUpForm/index.tsx
  pages/register/[uuid].js
Labels: enhancement

#571 chore: standardize buttons using a button component
  components/Button/index.tsx
  components/Layout/Layout.tsx
  components/QRScanner/index.jsx
  layout/Attendee/Profile/Profile.tsx
  layout/Attendee/Wheel/Wheel.tsx
  layout/Challenges/components/Challenges/Challenge/index.tsx
  layout/Hackathon/components/Hero/index.jsx
  layout/Hackathon/components/Regulations/index.jsx
  layout/Home/components/Hackathon/index.jsx
  layout/Home/components/Hero/Pitch/index.jsx
  layout/Home/components/Speakers/index.jsx
  layout/Login/components/LoginForm/index.tsx
  layout/Product/Product.tsx
  layout/ResetPassword/components/ResetPasswordForm/index.tsx
  layout/SignUp/components/SignUpForm/index.tsx
  layout/Staff/Prize/Prize.tsx
  layout/Staff/components/StaffRedeemButton/index.jsx
  layout/moonstone/sponsor/dashboard/SponsorBadgeButton/index.jsx
  layout/moonstone/sponsor/dashboard/SponsorPrizeButton/index.jsx
  layout/moonstone/sponsor/spotlight/SpotlightButton/index.jsx
  layout/shared/Leaderboard/Leaderboard.tsx
  pages/register/[uuid].js
Labels: enhancement, priority:medium
